### ISSUE TITLE
Indirect dependencies are not included in import paths

### ISSUE THREAD

**Issue by yshui** [atilaneves/reggae#11]
I have a project that depends on DerelictSDL2, and DerelictSDL2 depends on DerelictUtils.

When I tried to build it with reggae, only DerelictSDL2 is listed in import path, and the project failed to build.

**Comment by atilaneves** [comment]
I'm assuming you have a `dub.json`? Could you post it please and tell me what the exact issue is? If possible, a link to your repository, as well. If not, that's ok, but I'll need more than this to diagnose the problem. Thanks.

**Comment by yshui** [comment]
I create a simple test case: https://github.com/yshui/reggae-test

**Comment by atilaneves** [comment]
This seems to be a `dub` bug. When I tried `dub describe` on the test project, I got this:

    Error executing command describe:
    ~/coding/d/reggae-test/dub.json(0): Error: JSON string is empty.

**Comment by yshui** [comment]
@atilaneves dub describe runs fine here. result: http://dpaste.com/1WE8WGW

**Comment by atilaneves** [comment]
My bad, I accidentally deleted the `dub.json` in my clone. This is definitely a reggae bug.
