### ISSUE TITLE
Can't set executable as dependency

### ISSUE THREAD

**Issue by yshui** [atilaneves/reggae#12]
This is a common use case for code generation, the code generation Target needs to depend on the tool used to generate the code.

And the executable() function is not usable at compile time

**Comment by yshui** [comment]
I think reggae should not define the main function, otherwise users not limited to use only comile-time Targets

**Comment by yshui** [comment]
Also when I have an executable Exe1 and a target A which depends on Exe1. If I create a Build with both Exe1 and A, then Exe1 will be build twice.

**Comment by atilaneves** [comment]
If you mean adding a dependency on reggae itself, then that's automatically done already.

If you mean your project generates code and you want the generation to depend on the generator, just add it as an implicit dependency. It's hard to know what you want to do without an example reggaefile.

**Comment by yshui** [comment]
The problem is that:

```d
alias app = executable!(App("src/main.d", "myapp"),
                        Flags("-g -debug"),
                        ImportPaths(["/path/to/imports"])
                        );
const code_gen = Target("out.c", "myapp in.txt", [app, "in.txt"]);
```
doesn't work, because executable() is not a comile time function

**Comment by atilaneves** [comment]
There are two things that don't work in your example above:

1. `"in.txt"` should be `Target("in.txt")` in the `code_gen` definition
2. `Target` is a regular value, and passing in `app` as a dependency doesn't work since it'll try and run the app at compile-time

With that in mind, this would have worked:

    import reggae;
    alias app = executable!(App("src/main.d", "myapp"),
                            Flags("-g -debug"),
                            ImportPaths(["/path/to/imports"])
                            );
    Build b() { //any name will do
        const code_gen = Target("out.c", "myapp in.txt", [app, Target("in.txt")]);
        return Build(code_gen);
    }

I understand and agree that having to declare a function for this is a nuisance, I'll have to think about how to make this easier.

**Comment by atilaneves** [comment]
With the fix, this works (notice that myapp is now an implicit dependency, as it should be):

    import reggae;
    alias app = executable!(App("src/main.d", "$builddir/myapp"),
                               Flags("-g -debug"),
                               ImportPaths(["/path/to/imports"])
                               );
    alias code_gen = target!("out.c", "./myapp $in $out", target!"in.txt", app);
    mixin build!(code_gen);
