### ISSUE TITLE
Same target built multiple times

### ISSUE THREAD

**Issue by yshui** [atilaneves/reggae#13]
Simple example:

```d
import reggae;

const ao = objectFile(SourceFile("a.c"));
const bo = objectFile(SourceFile("b.c"));
const co = objectFile(SourceFile("c.c"));
const t1 = Target("b", "gcc -o$out $in", [ao, bo]);
const t2 = Target("c", "gcc -o$out $in", [ao, co]);
mixin build!(t1, t2);
```

a.c will be compiled twice, which is unnecessary.

**Comment by atilaneves** [comment]
CMake would do the same thing. If you want to use the same source file with the same flags for two different binaries, use a static library. Unfortunately a convenience function for that is currently on my TODO list, so you'd have to specify the commands manually. Just make sure the lib is in the build directory by starting its output name with `$builddir`.

**Comment by yshui** [comment]
Can you give an example how to create static library? Because this doesn't work:

```d
import reggae;

const ao = objectFile(SourceFile("a.c"));
const liba = Target("liba.a", "ar rcs liba.a a.o", [ao]);
const bo = objectFile(SourceFile("b.c"));
const co = objectFile(SourceFile("c.c"));
const t1 = Target("b", "gcc -o$out $in", [liba, bo]);
const t2 = Target("c", "gcc -o$out $in", [liba, co]);
mixin build!(t1, t2);
```
liba will be built twice.

It'll be fine if _some_ targets are guaranteed to be built only once, but currently any target will be built multiple times if it appeared in the dependencies multiple times.

**Comment by yshui** [comment]
Oh, know I understand. To prevent a target to be built again, I have to manually set it's output path to be under $builddir.

Maybe you can put this into the document?

**Comment by atilaneves** [comment]
[This commit](https://github.com/atilaneves/reggae/commit/607b7121e62e0a9d25f583e623df7dac41758aab) introduced the `staticLibrary` rule, so it should be a lot easier from now on.
