### ISSUE TITLE
$builddir not expanded when target is not builtin as dependency

### ISSUE THREAD

**Issue by yshui** [atilaneves/reggae#14]
In this example, $builddir in target liba is expanded,
```d 
import reggae;

const ao = objectFile(SourceFile("a.c"));
const liba = Target("$builddir/liba.a", "ar rcs liba.a a.o", [ao]);
const bo = objectFile(SourceFile("b.c"));
const co = objectFile(SourceFile("c.c"));
const t1 = Target("b", "gcc -o$out $in", [liba, bo]);
const t2 = Target("c", "gcc -o$out $in", [liba, co]);
mixin build!(t1, t2);
```

But in this example, it is not:

```d
import reggae;

const ao = objectFile(SourceFile("a.c"));
const liba = Target("$builddir/liba.a", "ar rcs liba.a a.o", [ao]);
mixin build!(liba);
```

**Comment by atilaneves** [comment]
In the 2nd case, `$builddir` isn't necessary sincie now `liba.a` is a top-level target, but it's still a bug that it doesn't work. Also I'd write the liba rule like this:

    const liba = Target("$builddir/liba.a", "ar rcs $out $in", [ao]);

Notice the `$in` and `$out` variables instead.
