### ISSUE TITLE
dub targetPath ignored for copyFiles artifacts of dub *dependencies*

### ISSUE THREAD

**Issue by kinke** [atilaneves/reggae#140]
#134 makes the `targetPath` almost fully usable - build artifacts and `copyFiles` of the dub project itself end up in the right dir. But `copyFiles` of dub package dependencies still end up in the build/project dir (the same in my case, so I don't know exactly). In practice meaning that a lot of transitive DLL dependencies aren't copied to the right dir.

**Comment by atilaneves** [comment]
I'm not sure I understand - copying dlls is done so that they can be found at runtime so surely one would want them to end up where the produced binary is?

**Comment by kinke** [comment]
> surely one would want them to end up where the produced binary is

Exactly, but that's not what happens. The binary and `copyFiles` of the project itself are copied to `targetPath`, all `copyFiles` artifacts of *dependencies* are copied to the build/project dir though.
