### ISSUE TITLE
Redundant work for multiple configurations

### ISSUE THREAD

**Issue by kinke** [atilaneves/reggae#144]
For a dub project with multiple Windows configurations, reggae seems to repeat steps for each config, slowing down the reggae invocation considerably. Here's an excerpt from a CI log; the prepended timestamps need to be taken with a grain of salt (missing flushes from reggae side?):
```
…
21:31:57 [Reggae]   +40.018s  Fetched dub packages
21:31:57 [Reggae]   +40.107s      Getting dub build information
21:31:57 Copying files for core...
21:31:57 Copying files for symmetry.bloomberg...
21:31:57 Copying files for vibe-d:tls...
21:31:57 Copying files for symmetry-carbon...
21:31:57 Copying files for extra...
21:31:57 Copying files for sil-repl...
21:33:07 Dynamic libraries are not yet supported as dependencies - building as static library.
21:33:07 Dynamic libraries are not yet supported as dependencies - building as static library.
21:33:07 Configuration 'library' of package symmetry.kalstd contains no source files. Please add {"targetType": "none"} to its package description to avoid building it.
21:33:07 Dynamic libraries are not yet supported as dependencies - building as static library.
21:33:07 [Reggae]   +57.232s  Executing pre-build command `cd /d "C:\s\stdlib\core\cpp" && cmake . -G %VS_CMAKE_GENERATOR% -A x64 -DCMAKE_GENERATOR_INSTANCE="%VS_INSTALL_PATH%" && cmake --build . --config Release`
21:33:07 [Reggae]   +66.544s  Executing pre-build command `C:\Users\packer\AppData\Local\dub\packages\xlsxd-3.2.1\xlsxd\windepbuild.bat`
21:33:07 Copying files for core...
21:33:07 Copying files for symmetry.bloomberg...
21:33:07 Copying files for vibe-d:tls...
21:33:07 Copying files for symmetry-carbon...
21:33:07 Copying files for extra...
21:33:07 Copying files for sil-repl...
21:33:17 Dynamic libraries are not yet supported as dependencies - building as static library.
21:33:17 Dynamic libraries are not yet supported as dependencies - building as static library.
21:33:17 Configuration 'library' of package symmetry.kalstd contains no source files. Please add {"targetType": "none"} to its package description to avoid building it.
21:33:17 Dynamic libraries are not yet supported as dependencies - building as static library.
21:33:17 [Reggae]  +127.279s  Executing pre-build command `cd /d "C:\s\stdlib\core\cpp" && cmake . -G %VS_CMAKE_GENERATOR% -A x64 -DCMAKE_GENERATOR_INSTANCE="%VS_INSTALL_PATH%" && cmake --build . --config Release`
21:33:17 [Reggae]  +128.607s  Executing pre-build command `C:\Users\packer\AppData\Local\dub\packages\xlsxd-3.2.1\xlsxd\windepbuild.bat`
21:33:17 Copying files for core...
21:33:17 Copying files for symmetry.bloomberg...
21:33:17 Copying files for vibe-d:tls...
21:33:17 Copying files for symmetry-carbon...
21:33:17 Copying files for extra...
21:33:17 Copying files for sil-repl...
21:33:38 [Reggae]  +136.966s  Executing pre-build command `cd /d "C:\s\stdlib\core\cpp" && cmake . -G %VS_CMAKE_GENERATOR% -A x64 -DCMAKE_GENERATOR_INSTANCE="%VS_INSTALL_PATH%" && cmake --build . --config Release`
21:33:38 [Reggae]  +138.279s  Executing pre-build command `C:\Users\packer\AppData\Local\dub\packages\xlsxd-3.2.1\xlsxd\windepbuild.bat`
21:33:38 [Reggae]  +146.575s      Got     dub build information
…
```

**Comment by atilaneves** [comment]
I'm pretty sure the timestamps are accurate, but who knows.

What's the alternative to getting the correct information for each configuration? Limiting which ones are queried via command line arguments?

The repetition is from dub code (as can be seen by the lack of timestamps).

**Comment by kinke** [comment]
> I'm pretty sure the timestamps are accurate, but who knows.

I meant this divergence:
```
21:33:07 [Reggae]   +57.232s …
21:33:07 [Reggae]   +66.544s …
```

> What's the alternative to getting the correct information for each configuration? Limiting which ones are queried via command line arguments?

No idea; in our case, we're mostly building one config at a time per CI job. A cmdline option restricting to a single dub config, not just for querying but also as build target would come in handy and be a partial workaround for #141 (at least no more extra `reggaefile.d` for non-default configs).

Right now, executing reggae takes longer than 50% of the raw build time for the REPL here (2:38 mins for reggae, 5:07 for the build with ninja); with `getting dub build information` taking a whopping 1:46 minutes (dub fetching only 0:40 in comparison…).

**Comment by atilaneves** [comment]
> I meant this divergence:

11s for a C++ build seems pretty normal to me, on the low side even.

> in our case, we're mostly building one config at a time per CI job

Right, but in the general case there's no way to know which configurations are going to be used until the reggaefile gets compiled. Maybe all but one is optional but they're all there.

I think the best way forward here is to add a command-line option to constrain which dub configurations the user cares about.

> (dub packages fetching only 0:40 in comparison…).

Multithreaded fetch!

Now time dub doing the same thing ;)

**Comment by kinke** [comment]
> 11s for a C++ build seems pretty normal to me, on the low side even.

The point is that reggae doesn't seem to flush after outputting a line, so the info that it's about to do something that takes long may only appear after it's been done already. The prepended timestamps (not the reggae timestamps) are from the CI runner, which prepends the timestamp when the line makes it to stdout/err.

> I think the best way forward here is to add a command-line option to constrain which dub configurations the user cares about.

Sounds good.

> Now time dub doing the same thing ;)

No time really for this, but what on earth is it doing all the remaining time? With 8 parallel jobs, running reggae takes longer than the build...
