### ISSUE TITLE
Enable colored D compiler output with ninja backend

### ISSUE THREAD

**Issue by kinke** [atilaneves/reggae#149]
Ninja redirects stderr of launched processes (contrary to `make` apparently); both DMD and LDC react by not using ANSI color codes in their output. Reggae could implicitly enforce colors via `-color=on` (dmd/ldmd2) / `-enable-color` (ldc2). It does no harm because ninja takes care of stripping escape codes in case its stdout (seems to use stdout only) is redirected (can be overridden via env var `CLICOLOR_FORCE=1`). These ANSI color codes even work in Windows terminals of recent Win10 versions (ninja enables according flags).

**Comment by atilaneves** [comment]
Pretty sure this fixed it already: https://github.com/atilaneves/reggae/pull/147

**Comment by kinke** [comment]
Oh, I had no idea. :) - Well, sort-of - with make and a redirected stderr, you now enforce the escape codes in any case. Restricting it to ninja only would be perfect.

**Comment by atilaneves** [comment]
> with make and a redirected stderr, you now enforce the escape codes in any case

Is that a big deal? Otherwise I have to pass in the backed to dcompile.

**Comment by kinke** [comment]
Definitely not for me, but some people might not want strange characters in some log file. AFAICT, you're appending the flag at the end, so that the user cannot override it via `--dflags=-color=off`.

**Comment by atilaneves** [comment]
I tried... this seems like way too much work for little benefit.
