### ISSUE TITLE
Question about binary size

### ISSUE THREAD

**Issue by o3o** [atilaneves/reggae#164]
I have an app (wa111) with vibe.d.

When I compile with dub:
```
$ time dub build -q --compiler=ldc -brelease
Executed in   27.40 secs  ...
$ exa -l
.rwxr-xr-x 5.9M o3o 24 Apr 10:51 wa111  
```
so, slow but "compact" (~6M)

With reggae/ninja:
```
$ cd build
$ reggae --dc ldc2 -dflags=--release -b ninja ..
$ time ninja
Executed in    5.62 secs    fish           external
 
$ exa -l 
.rwxr-xr-x  26M o3o 24 Apr 10:48 wa111
```

very very fast but "big" (26M)

There is a way to have them both, fast and compact ? (_one ring to rule.._)

Thank you very much.

**Comment by atilaneves** [comment]
That's bizzare, what happens if you use `--all-at-once`?

**Comment by o3o** [comment]
```
$ reggae --dc ldc2 -dflags=--release --all-at-once -b ninja ..
```

same result...


So, if I run (without `--release`}
```
dub build -q --compiler=ldc 
$ exa -l 
.rwxr-xr-x 27M dao 29 Apr 15:33 wa111
```
size (27M) is about the same as that obtained with reggae (with `release`)  ...maybe the porblem is on `--release` flag?

**Comment by atilaneves** [comment]
The only difference between using dub and reggae is that the latter would build per D package by default, so I have no idea what's going on.
