### ISSUE TITLE
[Question] How does Reggae _work_? Internal documentation please

### ISSUE THREAD

**Issue by AravK** [atilaneves/reggae#40]
I want to make a Reggae-like project. I really like the way the current one works, with the single `import reggae;` pulling in a whole build system that you can use, but there's a problem. I'm looking at the source, and I _cannot_ tell where does Reggae start working up. It's not with the `mixin build!(...);` or a custom `Build` function, but some default code that executes when importing Reggae, that starts of the chain of functions that actually _do stuff_. Could you please explain (somewhere) how thing whole thing works? What does Reggae do with the `reggaefile.d`, how does the file work, etc. etc.

**Comment by atilaneves** [comment]
The internals could change at any time - documenting a moving target isn't fun.

No code executes when importing reggae - D doesn't let you do that. When reggae (when used as an executable, i.e. the default) runs, it writes some source code to the file system under `.reggae` in the build directory, and then compiles that together with the `reggaefile.d`, producing an executable (usually called `buildGen`, but called `build` if the binary backend is used). That executable is then run to produce the make/ninja/tup files(s).

I'd recommend examining the `.reggae` directory that's created after reggae is run.

**Comment by AravK** [comment]
Thanks! That's great help!
