### ISSUE TITLE
Support python 2 and 3

### ISSUE THREAD

**Issue by rjframe** [atilaneves/reggae#43]
Some Linux distributions (e.g., Ubuntu) make the "python" executable refer to python 2 and "python3" is python 3; Others, like Arch, make "python" python 3 and "python2" python 2. I'd like to use v3 for my reggaefile in a project consistently but this requires some work...

What makes sense to me is to look for something like a "REGGAE_PYTHON" environment variable that points to the python path, and call python via that value; if the variable doesn't exist, just call "python" like reggae does now. I can export my python path, but this doesn't mess up anyone that doesn't care, and we don't try to guess anything.

I can do the work for this, but don't know how you'd want it done.

**Comment by atilaneves** [comment]
The Pythonic way to resolve this is by using a virtualenv. Just make `python` be whatever version you need.

**Comment by rjframe** [comment]
Well, a virtualenv seems like overkill for something that isn't a python project though. Apache Spark uses a `PYSPARK_PYTHON` environment variable, though I don't know what other systems use to know whether this is common.

**Comment by atilaneves** [comment]
I see. Free free to create a PR. Your `REGGAE_PYTHON` idea seems good, just implement that via `environment.get("REGGAE_PYTHON", "python")` when calling the Python executable. I'll add a test for it later.

**Comment by rjframe** [comment]
Thanks. I've submitted a PR - the build error is due to a network error retrieving a ruby gem.

And thanks for reggae - this is awesome.

**Comment by atilaneves** [comment]
@rjframe Thanks for the PR and the kind words!
