### ISSUE TITLE
dub targetPath ignored

### ISSUE THREAD

**Issue by John-Colvin** [atilaneves/reggae#48]
targets always end up in the root dir.

**Comment by atilaneves** [comment]
This one is tricky, since if the user wants the binaries to be a different directory, then reggae should just be run from a different directory. I'd say it's not a bug. Feel free to reopen if you disagree.

**Comment by John-Colvin** [comment]
I feel like it's pretty important to be consistent with dub here. postBuildCommands, copyFiles and so on might need this to be as expected.

It's perfectly reasonable behaviour to spit things out in the `pwd`, but if the build config is being read from `dub` then I think it makes more sense to follow the instructions as given.

I can't reopen, don't have permissions.

**Comment by atilaneves** [comment]
Can you give an example of how `postBuildCommands` or `copyFiles` would fail if this issue isn't fixed?
