### ISSUE TITLE
doesn't work with my libs

### ISSUE THREAD

**Issue by adamdruppe** [atilaneves/reggae#62]
Make a simple little dub package:

dub.json
```
{
        "name": "dubtest",
        "dependencies": {
                "arsd-official:nanovega" : "*"
        }
}
```

source/app.d
```
import arsd.simpledisplay;
import arsd.nanovega;

void main () {
}
```

`dub run` works, doing nothing of course.

```
$ dub run reggae -- -b make
```

seems to work but then

```
$ make
```

spams undefined reference; it apparently didn't link in the library modules.

```
$  dub run reggae -- -b ninja
$ ninja
ninja: error: build.ninja:18: multiple rules generate .reggae/objs/dubtest.objs/home/me/.dub/packages/arsd-official-4.3.4/arsd-official.o [-w dupbuild=err]
```

**Comment by adamdruppe** [comment]
```
$ dub run reggae -- -b binary
$ ./build
```
also spams linker errors

**Comment by atilaneves** [comment]
arsd-official has a rather... unorthodox source tree structure for dub packages. Since all the D modules are in the same directory, they're in the same D package (arsd), which makes reggae's by-default "build per D package" completely fail. Here's a workaround:

```d
// reggaefile.d
import reggae;

enum commonFlags = "-w -g -debug";

alias default_ = dubDefaultTarget!(
    CompilerFlags(commonFlags),
    LinkerFlags(),
    CompilationMode.module_,
);

alias ut = dubTestTarget!(
    CompilerFlags(commonFlags),
    LinkerFlags(),
    CompilationMode.module_,
);

mixin build!(default_, ut);

```

**Comment by atilaneves** [comment]
(the default compilation mode is `CompilationMode.package_), the workaround above basically justs adds `CompilationMode.module_` to the regagefile that's generated by reggae when the file doesn't exist.

**Comment by adamdruppe** [comment]
On Thu, Dec 19, 2019 at 05:08:41AM -0800, Atila Neves wrote:
> arsd-official has a rather... unorthodox source tree structure for dub packages.

But it works with dub because I list the specific files necessary in the
dub config.

It also just works with dmd which reads the dependencies from the module
instead of making assumptions from the filesystem.


I'll try sticking the reggaefile in the repo too though, if it works,
whatever, good enough for me.

**Comment by atilaneves** [comment]
> But it works with dub 

It works with dub because dub (IMHO wrongly) builds a dub package all-at-once.

> It also just works with dmd

If you pass in all .d files at once, yes. Or if you manually build per D package and carefully select different object file names for each dub subpackage.

What was happening is that reggae was generating rules to build each D package separately, and it names object files accordingly (foo.bar -> foo/bar.o). In this case, each dub subpackage is in the same D package (arsd), so each of them was getting a rule to generate an arsd.o file, but from different D modules!

I *could* make the naming for each D package's object file smarter.

**Comment by adamdruppe** [comment]
On Thu, Dec 19, 2019 at 07:25:21AM -0800, Atila Neves wrote:
> It works with dub because dub (IMHO wrongly) builds a dub package all-at-once.

With my things, dub sees subpackages for each module (basically) and
compiles them independently as libraries, then links all those libraries
together.

So the :nanovega for example just has nanovega.d as a library. Then
it depends on :simpledisplay which builds simpledisplay.d as a lib,
depending on :color_base which does color.d as a lib.

Then all three generated libs are linked together.

This was a pain to write in dub.json btw, but it is all there and
all works now that it is written.

> If you pass in all .d files at once, yes.

Or just use `dmd -i` which automatically figures out which ones are
necessary and leaves the others out. dmd -i is wonderful.

> What was happening is that reggae was generating rules to build each D package separately, and it names object files accordingly (foo.bar -> foo/bar.o). In this case, each dub subpackage is in the same D package (arsd), so each of them was getting a rule to generate an arsd.o file, but from different D modules!

I see. That sounds like it is potentially a general problem:
suppose you have two things that use deimos packages.

// dependency A
import deimos.linenoise;

// dependency B
import deimos.sndfile;

Both those actually exist, but have nothing to do with each
other, other than being under the deimos namespace for C
bindings. They are separate git repos, they'd surely be
separate dub packages (if they were dub packages) and likely
thus be separate dependencies.

> I *could* make the naming for each D package's object file smarter.

A possible fix would be to just change it from

d_package.o

to

dub_package_name-d_package.o

so like my thing would thus generate

arsd-official__nanovega-arsd.o

or whatever (the __ there is to represent the : in the subpackage
identifier).

and that should eliminate the conflicts...

**Comment by atilaneves** [comment]
> This was a pain to write in dub.json btw, but it is all there and
all works now that it is written.

I understand that.

> Or just use `dmd -i` which

Which, IIUC, compiles everything at once.

> I see. That sounds like it is potentially a general problem:

Could be, yes. I might have to change the naming.
