### ISSUE TITLE
Allow compiling dub projects in other directories than root

### ISSUE THREAD

**Issue by nawordar** [atilaneves/reggae#79]
I had been building my project with Meson, but it stopped compiling due to a Meson bug. I thought that I could use Reggae instead, but I have Qt/C++ project in a root directory and my D project symlinked to `subprojects/d-library` so I can't use `dubDefaultTarget`. What about adding an optional argument to `dubDefaultTarget` for using a different root? I know that dub supports `--root` flag in the command line, so this should be possible.

**Comment by atilaneves** [comment]
I'm not sure I understand. 

I nearly never use reggae and build in the root directory. Nearly always this is what I do:

```
% mkdir bin
% reggae -b ninja ..
% ninja
```

What happens exactly in your case?

**Comment by nawordar** [comment]
I would like to do the same thing as I have done with Meson. I have a C++ project that depends on a D subproject located in `<project>/subprojects/d-library`. Meson then compiles the `d-library` first and root project second.
What I want to do here, is to create a main C++ `Target` depending on a D subproject in `<project>/subprojects/d-library`.

**Comment by atilaneves** [comment]
```d
enum dTarget = Target("subprojects/d-library/dlib.a", "cd subprojects/d-library && dub build", []);
enum cppTarget = Target("my_cpp_target", "command to build C++ target", dTarget);
```

**Comment by nawordar** [comment]
Thank you
