### ISSUE TITLE
Add API docs

### ISSUE THREAD

**Issue by JinShil** [atilaneves/reggae#9]
I'm hopeful for this tool.  Please generate some API documentation to make it more convenient to assess its value.

**Comment by atilaneves** [comment]
The reason there aren't any docs yet is because I don't know if I'm going to change everything all of a sudden. In the meanwhile you can read the feature files.

**Comment by atilaneves** [comment]
I've added some now. It's probably not enough. Let me know what you think.

**Comment by JinShil** [comment]
It's looking good, thanks!.  I hope to play more with this code this weekend.
